//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MindWeaveServer.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuestInvitations
    {
        public int invitation_id { get; set; }
        public int match_id { get; set; }
        public string guest_email { get; set; }
        public int inviter_player_id { get; set; }
        public System.DateTime sent_timestamp { get; set; }
        public System.DateTime expiry_timestamp { get; set; }
        public Nullable<System.DateTime> used_timestamp { get; set; }
    
        public virtual Matches Matches { get; set; }
        public virtual Player Player { get; set; }
    }
}
