//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MindWeaveServer.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Matches
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Matches()
        {
            this.MatchExpulsions = new HashSet<MatchExpulsions>();
            this.MatchParticipants = new HashSet<MatchParticipants>();
            this.GuestInvitations = new HashSet<GuestInvitations>();
        }
    
        public int matches_id { get; set; }
        public System.DateTime creation_time { get; set; }
        public Nullable<System.DateTime> start_time { get; set; }
        public Nullable<System.DateTime> end_time { get; set; }
        public int match_status_id { get; set; }
        public int puzzle_id { get; set; }
        public Nullable<int> difficulty_id { get; set; }
        public string lobby_code { get; set; }
    
        public virtual DifficultyLevels DifficultyLevels { get; set; }
        public virtual MatchStatus MatchStatus { get; set; }
        public virtual Puzzles Puzzles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MatchExpulsions> MatchExpulsions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MatchParticipants> MatchParticipants { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GuestInvitations> GuestInvitations { get; set; }
    }
}
