//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MindWeaveServer.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatchExpulsions
    {
        public int idMatchExpulsion { get; set; }
        public int match_id { get; set; }
        public int expelled_player_id { get; set; }
        public int host_player_id { get; set; }
        public int reason_id { get; set; }
        public System.DateTime expulsion_time { get; set; }
    
        public virtual ExpulsionReasons ExpulsionReasons { get; set; }
        public virtual Matches Matches { get; set; }
        public virtual Player Player { get; set; }
        public virtual Player Player1 { get; set; }
    }
}
