//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MindWeaveServer.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatchParticipants
    {
        public int match_participants_id { get; set; }
        public int match_id { get; set; }
        public int player_id { get; set; }
        public Nullable<bool> is_host { get; set; }
        public Nullable<int> score { get; set; }
        public Nullable<int> pieces_placed { get; set; }
        public Nullable<int> final_rank { get; set; }
    
        public virtual Matches Matches { get; set; }
        public virtual Player Player { get; set; }
    }
}
