//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MindWeaveServer.DataAccess
{
    using MindWeaveServer.Utilities;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MindWeaveDBEntities1 : DbContext
    {
        public MindWeaveDBEntities1()
            : base(SecureConnection.getConnectionString())
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Achievements> Achievements { get; set; }
        public virtual DbSet<DifficultyLevels> DifficultyLevels { get; set; }
        public virtual DbSet<ExpulsionReasons> ExpulsionReasons { get; set; }
        public virtual DbSet<Friendships> Friendships { get; set; }
        public virtual DbSet<Gender> Gender { get; set; }
        public virtual DbSet<Matches> Matches { get; set; }
        public virtual DbSet<MatchExpulsions> MatchExpulsions { get; set; }
        public virtual DbSet<MatchParticipants> MatchParticipants { get; set; }
        public virtual DbSet<MatchStatus> MatchStatus { get; set; }
        public virtual DbSet<Player> Player { get; set; }
        public virtual DbSet<PlayerStats> PlayerStats { get; set; }
        public virtual DbSet<Puzzles> Puzzles { get; set; }
        public virtual DbSet<RequestStatus> RequestStatus { get; set; }
        public virtual DbSet<GuestInvitations> GuestInvitations { get; set; }
        public virtual DbSet<PlayerSocialMedias> PlayerSocialMedias { get; set; }
        public virtual DbSet<SocialMediaPlatforms> SocialMediaPlatforms { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
