//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MindWeaveServer.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerSocialMedias
    {
        public int IdPlayerSocialMedia { get; set; }
        public int IdPlayer { get; set; }
        public int IdSocialMediaPlatform { get; set; }
        public string Username { get; set; }
    
        public virtual Player Player { get; set; }
        public virtual SocialMediaPlatforms SocialMediaPlatforms { get; set; }
    }
}
