//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MindWeaveServer.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerStats
    {
        public int player_id { get; set; }
        public Nullable<int> puzzles_completed { get; set; }
        public Nullable<int> puzzles_won { get; set; }
        public Nullable<int> total_playtime_minutes { get; set; }
        public Nullable<int> highest_score { get; set; }
    
        public virtual Player Player { get; set; }
    }
}
