//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MindWeaveServer.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MindWeaveServer.Resources.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en la conexión con la base de datos..
        /// </summary>
        public static string DatabaseConnectionError {
            get {
                return ResourceManager.GetString("DatabaseConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en la base de datos al iniciar la partida..
        /// </summary>
        public static string DatabaseErrorStartingMatch {
            get {
                return ResourceManager.GetString("DatabaseErrorStartingMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario ya existe..
        /// </summary>
        public static string DuplicateUserError {
            get {
                return ResourceManager.GetString("DuplicateUserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usa el siguiente código para unirte:.
        /// </summary>
        public static string EmailCodeInfoGuestInvite {
            get {
                return ResourceManager.GetString("EmailCodeInfoGuestInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu código de recuperación es:.
        /// </summary>
        public static string EmailCodeInfoPasswordRecovery {
            get {
                return ResourceManager.GetString("EmailCodeInfoPasswordRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este código expirará en {0} minutos..
        /// </summary>
        public static string EmailExpiryInfo {
            get {
                return ResourceManager.GetString("EmailExpiryInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Hola {0}!.
        /// </summary>
        public static string EmailGreeting {
            get {
                return ResourceManager.GetString("EmailGreeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Hola!.
        /// </summary>
        public static string EmailGreetingGuest {
            get {
                return ResourceManager.GetString("EmailGreetingGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicia Mind Weave, selecciona &apos;Jugar como Invitado&apos; e ingresa este código..
        /// </summary>
        public static string EmailHowToJoinGuest {
            get {
                return ResourceManager.GetString("EmailHowToJoinGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si no solicitaste esto, puedes ignorar este correo de forma segura..
        /// </summary>
        public static string EmailIgnoreInfo {
            get {
                return ResourceManager.GetString("EmailIgnoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} te ha invitado a unirte a una sala de rompecabezas en Mind Weave..
        /// </summary>
        public static string EmailInstructionGuestInvite {
            get {
                return ResourceManager.GetString("EmailInstructionGuestInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitaste restablecer tu contraseña para Mind Weave..
        /// </summary>
        public static string EmailInstructionPasswordRecovery {
            get {
                return ResourceManager.GetString("EmailInstructionPasswordRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gracias por registrarte. Usa el siguiente código para activar tu cuenta:.
        /// </summary>
        public static string EmailInstructionVerify {
            get {
                return ResourceManager.GetString("EmailInstructionVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Te han invitado a jugar Mind Weave!.
        /// </summary>
        public static string EmailSubjectGuestInvite {
            get {
                return ResourceManager.GetString("EmailSubjectGuestInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recuperación de Contraseña - Mind Weave.
        /// </summary>
        public static string EmailSubjectPasswordRecovery {
            get {
                return ResourceManager.GetString("EmailSubjectPasswordRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código de Verificación - Mind Weave.
        /// </summary>
        public static string EmailSubjectVerification {
            get {
                return ResourceManager.GetString("EmailSubjectVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Bienvenido a Mind Weave, {0}!.
        /// </summary>
        public static string EmailWelcome {
            get {
                return ResourceManager.GetString("EmailWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontró una cuenta asociada a esos datos..
        /// </summary>
        public static string ErrorAccountNotFound {
            get {
                return ResourceManager.GetString("ErrorAccountNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Todos los campos son requeridos..
        /// </summary>
        public static string ErrorAllFieldsRequired {
            get {
                return ResourceManager.GetString("ErrorAllFieldsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La ruta del avatar no puede estar vacía..
        /// </summary>
        public static string ErrorAvatarPathCannotBeEmpty {
            get {
                return ResourceManager.GetString("ErrorAvatarPathCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error inesperado al actualizar la ruta del avatar..
        /// </summary>
        public static string ErrorAvatarUpdateFailed {
            get {
                return ResourceManager.GetString("ErrorAvatarUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puedes eliminarte a ti mismo de la lista de amigos..
        /// </summary>
        public static string ErrorCannotRemoveSelf {
            get {
                return ResourceManager.GetString("ErrorCannotRemoveSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puedes enviarte una solicitud de amistad a ti mismo..
        /// </summary>
        public static string ErrorCannotSelfFriend {
            get {
                return ResourceManager.GetString("ErrorCannotSelfFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al establecer el canal de comunicación..
        /// </summary>
        public static string ErrorCommunicationChannelFailed {
            get {
                return ResourceManager.GetString("ErrorCommunicationChannelFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña actual es incorrecta..
        /// </summary>
        public static string ErrorCurrentPasswordIncorrect {
            get {
                return ResourceManager.GetString("ErrorCurrentPasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo enviar el correo. El servicio de email no está disponible..
        /// </summary>
        public static string ErrorEmailServiceUnavailable {
            get {
                return ResourceManager.GetString("ErrorEmailServiceUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No eres amigo de este jugador..
        /// </summary>
        public static string ErrorFriendshipNotFound {
            get {
                return ResourceManager.GetString("ErrorFriendshipNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo generar un nombre de usuario único para el invitado. Intenta con otro nombre..
        /// </summary>
        public static string ErrorGuestUsernameGenerationFailed {
            get {
                return ResourceManager.GetString("ErrorGuestUsernameGenerationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre de invitado deseado &apos;{0}&apos; ya está en uso en esta sala. Intentando otro....
        /// </summary>
        public static string ErrorGuestUsernameTaken {
            get {
                return ResourceManager.GetString("ErrorGuestUsernameTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos de invitación inválidos. .
        /// </summary>
        public static string ErrorInvalidInvitationData {
            get {
                return ResourceManager.GetString("ErrorInvalidInvitationData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El código de invitación para este correo es inválido, ha expirado o ya fue usado..
        /// </summary>
        public static string ErrorInvalidOrExpiredGuestInvite {
            get {
                return ResourceManager.GetString("ErrorInvalidOrExpiredGuestInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al unirse a los datos del lobby..
        /// </summary>
        public static string ErrorJoiningLobbyData {
            get {
                return ResourceManager.GetString("ErrorJoiningLobbyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El servidor se encuentra inhabilitado. Intenta más tarde por favor..
        /// </summary>
        public static string ErrorMsgServerOffline {
            get {
                return ResourceManager.GetString("ErrorMsgServerOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontró una solicitud de amistad pendiente de este usuario..
        /// </summary>
        public static string ErrorNoPendingRequestFound {
            get {
                return ResourceManager.GetString("ErrorNoPendingRequestFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugador no encontrado..
        /// </summary>
        public static string ErrorPlayerNotFound {
            get {
                return ResourceManager.GetString("ErrorPlayerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Falta el archivo de imagen del rompecabezas del servidor..
        /// </summary>
        public static string ErrorPuzzleFileNotFound {
            get {
                return ResourceManager.GetString("ErrorPuzzleFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error del servidor durante la subida..
        /// </summary>
        public static string ErrorPuzzleUploadFailed {
            get {
                return ResourceManager.GetString("ErrorPuzzleUploadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos inválidos para la subida..
        /// </summary>
        public static string ErrorPuzzleUploadInvalidData {
            get {
                return ResourceManager.GetString("ErrorPuzzleUploadInvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontró el jugador que está subiendo la imagen..
        /// </summary>
        public static string ErrorPuzzleUploadPlayerNotFound {
            get {
                return ResourceManager.GetString("ErrorPuzzleUploadPlayerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al leer el archivo del rompecabezas desde el almacenamiento..
        /// </summary>
        public static string ErrorReadingPuzzleFile {
            get {
                return ResourceManager.GetString("ErrorReadingPuzzleFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al guardar el cambio de dificultad..
        /// </summary>
        public static string ErrorSavingDifficultyChange {
            get {
                return ResourceManager.GetString("ErrorSavingDifficultyChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo enviar la invitación de invitado. Inténtalo de nuevo..
        /// </summary>
        public static string ErrorSendingGuestInvitation {
            get {
                return ResourceManager.GetString("ErrorSendingGuestInvitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La conexión con el servicio se está cerrando..
        /// </summary>
        public static string ErrorServiceConnectionClosing {
            get {
                return ResourceManager.GetString("ErrorServiceConnectionClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al inicializar el servicio..
        /// </summary>
        public static string ErrorServiceInitializationFailed {
            get {
                return ResourceManager.GetString("ErrorServiceInitializationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La sesión no coincide..
        /// </summary>
        public static string ErrorSessionMismatch {
            get {
                return ResourceManager.GetString("ErrorSessionMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este usuario ya ha iniciado sesión en otro dispositivo..
        /// </summary>
        public static string ErrorUserAlreadyLoggedIn {
            get {
                return ResourceManager.GetString("ErrorUserAlreadyLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Usuario no esta en línea.
        /// </summary>
        public static string ErrorUserNotOnline {
            get {
                return ResourceManager.GetString("ErrorUserNotOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Amigo eliminado correctamente..
        /// </summary>
        public static string FriendRemovedSuccessfully {
            get {
                return ResourceManager.GetString("FriendRemovedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitud de amistad aceptada..
        /// </summary>
        public static string FriendRequestAccepted {
            get {
                return ResourceManager.GetString("FriendRequestAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitud de amistad ya enviada y pendiente..
        /// </summary>
        public static string FriendRequestAlreadySent {
            get {
                return ResourceManager.GetString("FriendRequestAlreadySent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este jugador ya te ha enviado una solicitud. Respóndela..
        /// </summary>
        public static string FriendRequestReceivedFromUser {
            get {
                return ResourceManager.GetString("FriendRequestReceivedFromUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitud de amistad rechazada..
        /// </summary>
        public static string FriendRequestRejected {
            get {
                return ResourceManager.GetString("FriendRequestRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitud de amistad enviada..
        /// </summary>
        public static string FriendRequestSent {
            get {
                return ResourceManager.GetString("FriendRequestSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya eres amigo de este jugador..
        /// </summary>
        public static string FriendshipAlreadyExists {
            get {
                return ResourceManager.GetString("FriendshipAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede enviar la solicitud debido a una relación existente..
        /// </summary>
        public static string FriendshipStatusPreventsRequest {
            get {
                return ResourceManager.GetString("FriendshipStatusPreventsRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error inesperado en el servidor..
        /// </summary>
        public static string GenericServerError {
            get {
                return ResourceManager.GetString("GenericServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El anfitrión salió del lobby..
        /// </summary>
        public static string HostLeftLobby {
            get {
                return ResourceManager.GetString("HostLeftLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu contraseña ha sido restablecida correctamente. Ya puedes iniciar sesión..
        /// </summary>
        public static string InfoPasswordResetSuccess {
            get {
                return ResourceManager.GetString("InfoPasswordResetSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha enviado un código de recuperación a tu correo electrónico..
        /// </summary>
        public static string InfoRecoveryCodeSent {
            get {
                return ResourceManager.GetString("InfoRecoveryCodeSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expulsado por el anfitrión..
        /// </summary>
        public static string KickedByHost {
            get {
                return ResourceManager.GetString("KickedByHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Has sido expulsado por lenguaje ofensivo (3 strikes)..
        /// </summary>
        public static string KickMessageProfanity {
            get {
                return ResourceManager.GetString("KickMessageProfanity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al generar un código único para el lobby..
        /// </summary>
        public static string lobbyCodeGenerationFailed {
            get {
                return ResourceManager.GetString("lobbyCodeGenerationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lobby creado exitosamente..
        /// </summary>
        public static string lobbyCreatedSuccessfully {
            get {
                return ResourceManager.GetString("lobbyCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos del lobby no encontrados..
        /// </summary>
        public static string LobbyDataNotFound {
            get {
                return ResourceManager.GetString("LobbyDataNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El lobby {0} está lleno..
        /// </summary>
        public static string LobbyIsFull {
            get {
                return ResourceManager.GetString("LobbyIsFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El lobby {0} ya no está disponible..
        /// </summary>
        public static string LobbyNoLongerAvailable {
            get {
                return ResourceManager.GetString("LobbyNoLongerAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El lobby {0} no existe o está inactivo..
        /// </summary>
        public static string lobbyNotFoundOrInactive {
            get {
                return ResourceManager.GetString("lobbyNotFoundOrInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El lobby no está en estado de espera..
        /// </summary>
        public static string LobbyNotInWaitingState {
            get {
                return ResourceManager.GetString("LobbyNotInWaitingState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al registrar el lobby en memoria después de guardar en la base de datos..
        /// </summary>
        public static string lobbyRegistrationFailed {
            get {
                return ResourceManager.GetString("lobbyRegistrationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu cuenta no ha sido verificada. Revisa tu correo.
        /// </summary>
        public static string LoginAccountNotVerified {
            get {
                return ResourceManager.GetString("LoginAccountNotVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El email o la contraseña son incorrectos..
        /// </summary>
        public static string LoginPasswordNotEmpty {
            get {
                return ResourceManager.GetString("LoginPasswordNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sesión iniciada..
        /// </summary>
        public static string LoginSuccessful {
            get {
                return ResourceManager.GetString("LoginSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay suficientes jugadores para iniciar..
        /// </summary>
        public static string NotEnoughPlayersToStart {
            get {
                return ResourceManager.GetString("NotEnoughPlayersToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No eres el anfitrión..
        /// </summary>
        public static string notHost {
            get {
                return ResourceManager.GetString("notHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo guardar la nueva contraseña..
        /// </summary>
        public static string PasswordChangedFailed {
            get {
                return ResourceManager.GetString("PasswordChangedFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu contraseña ha sido restablecida correctamente..
        /// </summary>
        public static string PasswordChangedSuccessfully {
            get {
                return ResourceManager.GetString("PasswordChangedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} ya está en el lobby..
        /// </summary>
        public static string PlayerAlreadyInLobby {
            get {
                return ResourceManager.GetString("PlayerAlreadyInLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El jugador &apos;{0}&apos; o la partida del lobby &apos;{1}&apos; no se encontraron en la base de datos..
        /// </summary>
        public static string PlayerOrMatchNotFoundInDb {
            get {
                return ResourceManager.GetString("PlayerOrMatchNotFoundInDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perfil actualizado correctamente.
        /// </summary>
        public static string ProfileUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("ProfileUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al actualizar el perfil.
        /// </summary>
        public static string ProfileUpdateFailed {
            get {
                return ResourceManager.GetString("ProfileUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro exitoso. Se ha enviado un código de verificación a tu correo electrónico..
        /// </summary>
        public static string RegistrationSuccessful {
            get {
                return ResourceManager.GetString("RegistrationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre de usuario o el correo electrónico ya están en uso..
        /// </summary>
        public static string RegistrationUsernameOrEmailExists {
            get {
                return ResourceManager.GetString("RegistrationUsernameOrEmailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Avatar actualizado correctamente..
        /// </summary>
        public static string SuccessAvatarUpdated {
            get {
                return ResourceManager.GetString("SuccessAvatarUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Te has unido a la sala como invitado..
        /// </summary>
        public static string SuccessGuestJoinedLobby {
            get {
                return ResourceManager.GetString("SuccessGuestJoinedLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Imagen subida con éxito!.
        /// </summary>
        public static string SuccessPuzzleUpload {
            get {
                return ResourceManager.GetString("SuccessPuzzleUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rompecabezas subido exitosamente..
        /// </summary>
        public static string SuccessPuzzleUploaded {
            get {
                return ResourceManager.GetString("SuccessPuzzleUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debes tener al menos 13 años para registrarte..
        /// </summary>
        public static string ValidationDateOfBirthMinimumAge {
            get {
                return ResourceManager.GetString("ValidationDateOfBirthMinimumAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La fecha de nacimiento no parece realista..
        /// </summary>
        public static string ValidationDateOfBirthRealistic {
            get {
                return ResourceManager.GetString("ValidationDateOfBirthRealistic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La fecha de nacimiento es obligatoria.
        /// </summary>
        public static string ValidationDateOfBirthRequired {
            get {
                return ResourceManager.GetString("ValidationDateOfBirthRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El formato del correo electrónico no es válido..
        /// </summary>
        public static string ValidationEmailFormat {
            get {
                return ResourceManager.GetString("ValidationEmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El correo electrónico es obligatorio..
        /// </summary>
        public static string ValidationEmailRequired {
            get {
                return ResourceManager.GetString("ValidationEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dificultad seleccionada no válida.
        /// </summary>
        public static string ValidationErrorDifficultyInvalid {
            get {
                return ResourceManager.GetString("ValidationErrorDifficultyInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre no puede exceder los 45 caracteres..
        /// </summary>
        public static string ValidationFirstNameLength {
            get {
                return ResourceManager.GetString("ValidationFirstNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre es obligatorio..
        /// </summary>
        public static string ValidationFirstNameRequired {
            get {
                return ResourceManager.GetString("ValidationFirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El apellido no puede exceder los 45 caracteres..
        /// </summary>
        public static string ValidationLastNameLength {
            get {
                return ResourceManager.GetString("ValidationLastNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los apellidos son requeridos..
        /// </summary>
        public static string ValidationLastNameRequired {
            get {
                return ResourceManager.GetString("ValidationLastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo no puede comenzar ni terminar con espacios..
        /// </summary>
        public static string ValidationNoLeadingOrTrailingWhitespace {
            get {
                return ResourceManager.GetString("ValidationNoLeadingOrTrailingWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este campo solo puede contener letras..
        /// </summary>
        public static string ValidationOnlyLetters {
            get {
                return ResourceManager.GetString("ValidationOnlyLetters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña debe incluir al menos una mayúscula, una minúscula y un número.
        /// </summary>
        public static string ValidationPasswordComplexity {
            get {
                return ResourceManager.GetString("ValidationPasswordComplexity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña debe tener al menos 8 caracteres..
        /// </summary>
        public static string ValidationPasswordLength {
            get {
                return ResourceManager.GetString("ValidationPasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña no puede contener espacios..
        /// </summary>
        public static string ValidationPasswordNoSpaces {
            get {
                return ResourceManager.GetString("ValidationPasswordNoSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña no puede estar vacía.
        /// </summary>
        public static string ValidationPasswordRequired {
            get {
                return ResourceManager.GetString("ValidationPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El perfil de usuario y la contraseña son obligatorios..
        /// </summary>
        public static string ValidationProfileOrPasswordRequired {
            get {
                return ResourceManager.GetString("ValidationProfileOrPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El jugador {0} ya se encuentra en una partida..
        /// </summary>
        public static string ValidationUserAlreadyInGame {
            get {
                return ResourceManager.GetString("ValidationUserAlreadyInGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre de usuario solo puede contener letras y números..
        /// </summary>
        public static string ValidationUsernameAlphanumeric {
            get {
                return ResourceManager.GetString("ValidationUsernameAlphanumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre de usuario debe tener entre 3 y 16 caracteres.
        /// </summary>
        public static string ValidationUsernameLength {
            get {
                return ResourceManager.GetString("ValidationUsernameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre de usuario no puede estar vacío..
        /// </summary>
        public static string ValidationUsernameRequired {
            get {
                return ResourceManager.GetString("ValidationUsernameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esta cuenta ya ha sido verificada..
        /// </summary>
        public static string VerificationAccountAlreadyVerified {
            get {
                return ResourceManager.GetString("VerificationAccountAlreadyVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El código de verificación solo debe contener 6 números..
        /// </summary>
        public static string VerificationCodeInvalidFormat {
            get {
                return ResourceManager.GetString("VerificationCodeInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El correo electrónico y el código son obligatorios..
        /// </summary>
        public static string VerificationEmailAndCodeRequired {
            get {
                return ResourceManager.GetString("VerificationEmailAndCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontró una verificación pendiente para este correo..
        /// </summary>
        public static string VerificationEmailNotFound {
            get {
                return ResourceManager.GetString("VerificationEmailNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código de verificación inválido o expirado..
        /// </summary>
        public static string VerificationInvalidOrExpiredCode {
            get {
                return ResourceManager.GetString("VerificationInvalidOrExpiredCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuenta verificada correctamente. Ya puedes iniciar sesión..
        /// </summary>
        public static string VerificationSuccessful {
            get {
                return ResourceManager.GetString("VerificationSuccessful", resourceCulture);
            }
        }
    }
}
